load 'deploy'
# Uncomment if you are using Rails' asset pipeline
    # load 'deploy/assets'
# load 'config/deploy' # remove this line to skip loading any of the default tasks
require "capistrano/node-deploy"

set :application, "admin"
set :repository,  "https://goatrans.googlecode.com/svn/trunk/code/administration/admin_app"
set :user, "ubuntu"
set :scm, :subversion
set :deploy_to, "/home/ubuntu/deploytest"

role :app, "54.255.186.112"

# Set app command to run (defaults to index.js, or your `main` file from `package.json`)
#set :app_command, "my_server.coffee"

# Set additional environment variables for the app
set :app_environment, "PORT=8000"

# Set node binary to run (defaults to /usr/bin/node)
#set :node_binary, "/usr/bin/coffee"

# Set node environment (defaults to production)
set :node_env, "staging"

# Set the user to run node as (defaults to deploy)
set :node_user, "ubuntu"

# Set the name of the upstart command (defaults to #{application}-#{node_env})
#set :upstart_job_name, "myserver"

after "deploy:symlink", "deploy:minify"
#, "deploy:gae_upload"

namespace :deploy do
  task :minify, :roles => :app do
    run "cd #{ current_path }/public ; awk '/JS STARTS/{P=1;next }/JS ENDS/ {exit} P' ../views/admin.ejs | grep -v '^\s*$' | sed 's/.*=.\\(.*\\.js\\).*/\\1/' | xargs cat | minify -js > js/all.js"
  end

  task :gae_upload, :roles => :app do
    run "cd #{ current_path } ; echo 1goatrans2 | /home/ubuntu/google_appengine/appcfg.py --email=commuteguide@gmail.com --passin update ."
  end
  
    task :replace_static, :roles => :app do
    run "echo hi"
  end
end